### ISSUE TITLE
WWN from MegaCli not always match with /dev/disk/by-id

### ISSUE THREAD

**Issue by tclh123** [chicks-net/megamap#1]
WWN or SAS Addr from MegaCli not always match with /dev/disk/by-id, and the difference is uncertain(sometime 1, but sometime 2....)

**Comment by edrozenberg** [comment]
Don't think it's related to this issue but an interesting wwn related fact I noticed -
on two of my Seagate SAS drives, the WWN printed on the drive label has a last
digit that is different from the wwn reported by Linux and by sas2ircu.

Example:
Label printed on seagate drive - WWN: 5000C50057A 15E34
Reported by Linux /dev/disk/by-id - WWN: wwn-0x5000c50057a15e37
Reported by Linux sas2ircu:  GUID: 5000c50057a15e37

For other drives (some Micron ssd's, Western Digital drives) there is no discrepancy at all. Strange.

For purposes of ID'ing the drives I'm planning to either ignore the last digit or print out a label with
the "correct" wwn and stick it on those drives with the problem.

**Comment by chicks-net** [comment]
Thanks Ed, that's an interesting data point.  :chart:

**Comment by edrozenberg** [comment]
One more interesting data point: there's a third different ID coming from the SAS address in sas ircu:
5000c50-0-57a1-5e35 (compared with GUID 5000c50057a15e37 and drive label WWN: 5000C50057A 15E34). Won't bother me but wish the drive would make up its mind :).

Device is a Hard disk
  Enclosure #                             : 1
  Slot #                                  : 0
  SAS Address                             : 5000c50-0-57a1-5e35
  State                                   : Ready (RDY)
  Size (in MB)/(in sectors)               : 3815447/7814037167
  Manufacturer                            : SEAGATE 
  Model Number                            : ST4000NM0023    
  Firmware Revision                       : 0003
  Serial No                               : Z1Z2EAER
  GUID                                    : 5000c50057a15e37
  Protocol                                : SAS
  Drive Type                              : SAS_HDD
