### ISSUE TITLE
No output from megcali

### ISSUE THREAD

**Issue by zillurbmb51** [chicks-net/megamap#7]
Hi there,
I was using my 16 tb raid disk for few years. From last Friday I can't mount it. I googled and googled and tried different tools but no luck. When I use megamap I get:  sudo ./megamap  "No output from megacli
"
Here is some other info about this problem. Any help will be greatly appreciated. 

I was trying to mount it but failed.
megacli -LDInfo -LALL -aALL                                     

Exit Code: 0x00

My module is:
"[zillur@genomics megamap]$ modinfo megaraid_sas
filename:       /lib/modules/3.10.0-862.11.6.el7.x86_64/kernel/drivers/scsi/megaraid/megaraid_sas.ko.xz
description:    Avago MegaRAID SAS Driver
author:         megaraidlinux.pdl@avagotech.com
version:        07.702.06.00-rh2
license:        GPL
retpoline:      Y
rhelversion:    7.5
srcversion:     A19DC3530FA946F3FE5CCAD
alias:          pci:v00001000d0000001Csv*sd*bc*sc*i*
alias:          pci:v00001000d0000001Bsv*sd*bc*sc*i*
alias:          pci:v00001000d00000017sv*sd*bc*sc*i*
alias:          pci:v00001000d00000016sv*sd*bc*sc*i*
alias:          pci:v00001000d00000014sv*sd*bc*sc*i*
alias:          pci:v00001000d00000053sv*sd*bc*sc*i*
alias:          pci:v00001000d00000052sv*sd*bc*sc*i*
alias:          pci:v00001000d000000CFsv*sd*bc*sc*i*
alias:          pci:v00001000d000000CEsv*sd*bc*sc*i*
alias:          pci:v00001000d0000005Fsv*sd*bc*sc*i*
alias:          pci:v00001000d0000005Dsv*sd*bc*sc*i*
alias:          pci:v00001000d0000002Fsv*sd*bc*sc*i*
alias:          pci:v00001000d0000005Bsv*sd*bc*sc*i*
alias:          pci:v00001028d00000015sv*sd*bc*sc*i*
alias:          pci:v00001000d00000413sv*sd*bc*sc*i*
alias:          pci:v00001000d00000071sv*sd*bc*sc*i*
alias:          pci:v00001000d00000073sv*sd*bc*sc*i*
alias:          pci:v00001000d00000079sv*sd*bc*sc*i*
alias:          pci:v00001000d00000078sv*sd*bc*sc*i*
alias:          pci:v00001000d0000007Csv*sd*bc*sc*i*
alias:          pci:v00001000d00000060sv*sd*bc*sc*i*
alias:          pci:v00001000d00000411sv*sd*bc*sc*i*
depends:        
intree:         Y
vermagic:       3.10.0-862.11.6.el7.x86_64 SMP mod_unload modversions 
signer:         CentOS Linux kernel signing key
sig_key:        D4:11:5F:11:00:55:DB:56:C8:D6:05:AB:75:21:73:CF:B1:AC:54:D8
sig_hashalgo:   sha256
parm:           lb_pending_cmds:Change raid-1 load balancing outstanding threshold. Valid Values are 1-128. Default: 4 (int)
parm:           max_sectors:Maximum number of sectors per IO command (int)
parm:           msix_disable:Disable MSI-X interrupt handling. Default: 0 (int)
parm:           msix_vectors:MSI-X max vector count. Default: Set by FW (int)
parm:           allow_vf_ioctls:Allow ioctls in SR-IOV VF mode. Default: 0 (int)
parm:           throttlequeuedepth:Adapter queue depth when throttled due to I/O timeout. Default: 16 (int)
parm:           resetwaittime:Wait time in seconds after I/O timeout before resetting adapter. Default: 180 (int)
parm:           smp_affinity_enable:SMP affinity feature enable/disbale Default: enable(1) (int)
parm:           rdpq_enable: Allocate reply queue in chunks for large queue depth enable/disable Default: disable(0) (int)
parm:           dual_qdepth_disable:Disable dual queue depth feature. Default: 0 (int)
parm:           scmd_timeout:scsi command timeout (10-90s), default 90s. See megasas_reset_timer. (int)"

dmesg report:
"02:00.0 RAID bus controller [0104]: LSI Logic / Symbios Logic MegaRAID SAS-3 3108 [Invader] [1000:005d] (rev 02)
[zillur@genomics megamap]$ dmesg | grep -i raid
[    2.164013] megaraid_sas 0000:02:00.0: Waiting for FW to come to ready state
[    2.164017] megaraid_sas 0000:02:00.0: FW in FAULT state!!
[  106.261587] megaraid_sas 0000:02:00.0: Diag reset adapter never cleared megasas_adp_reset_fusion 3552
[  106.261593] megaraid_sas 0000:02:00.0: FW restarted successfully from megasas_init_fw!
[  136.261751] megaraid_sas 0000:02:00.0: Waiting for FW to come to ready state
[  136.261757] megaraid_sas 0000:02:00.0: FW in FAULT state!!
[  136.261772] megaraid_sas 0000:02:00.0: Failed from megasas_init_fw 5543"

Any Help?
Best Regards
Zillur

**Comment by chicks-net** [comment]
If `megacli` isn't producing output I'm not sure what to tell you.  My tool needs that output to be able to figure out anything.

https://serverfault.com/questions/919209/megacli-commands-return-exit-code-0x00-with-perc-h200 seems to indicate this happens when using a rebranded LSI card from Dell.

Beyond that I'd google or ask on https://serverfault.com/ or similar places.
