### ISSUE TITLE
Does megacli work the same way as MegaCli?

### ISSUE THREAD

**Issue by Yukti-09** [chicks-net/megamap#9]
Command:` yum install megacli`
Loaded plugins: changelog, verify, versionlock
No package megacli available.
  Maybe you meant: MegaCli
Error: Nothing to do

 Command: `yum install MegaCli`
Loaded plugins: changelog, verify, versionlock
Package MegaCli-8.07.14-1.noarch already installed and latest version
Nothing to do

Location: /opt/MegaRAID/MegaCli

**Comment by chicks-net** [comment]
The command used to be all in lower case.  A symlink can make the command available in lower case.

```
cd /opt/MegaRAID
ln -s MegaCLI megacli
```

Or you can tweak the source of the script to use the uppercase command name.
